#version: "3.9"
services:
  elasticsearch:
    image: elasticsearch:8.14.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=ulyana-bel-cluster-name
    ports:
      - 9200:9200
    #volumes:
    #  - ./deploy/esdata:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.14.3
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200 

  logstash:
    image: logstash:8.14.3
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "http://elasticsearch:9200"
    ports:
      - "5044:5044"
    volumes:
      - ./configs/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./configs/logstash/pipelines:/usr/share/logstash/config/pipelines
      - ./logs:/var/log/app/:ro
    depends_on:
          - elasticsearch

  nginx:
    image: nginx:stable-alpine3.21-perl
    ports:
      - "80:80"
    volumes:
      - ./logs:/var/log/nginx