input {
  file {
    path => "/var/log/app/*.log" # Путь ВНУТРИ контейнера Logstash, куда приходят логи
    start_position => "beginning"
    sincedb_path => "/dev/null"   # Чтобы для теста логи перечитывались при каждом перезапуске
  }
}

filter {
  grok {
    match => { "message" => '%{IPORHOST:client_ip} - - \[%{HTTPDATE:timestamp}\] "%{WORD:http_method} %{URIPATHPARAM:request} HTTP/%{NUMBER:http_version}" %{NUMBER:response_code:int} %{NUMBER:bytes_sent:int} "%{GREEDYDATA:referrer}" "%{GREEDYDATA:user_agent}" "%{GREEDYDATA:other}"' }
  }
  
  date {
    match => ["timestamp", "dd/MMM/yyyy:HH:mm:ss Z"]
    target => "@timestamp"
  }
  
  useragent {
    source => "user_agent"
    target => "user_agent_details"
  }
}



output {
  stdout {
    codec => rubydebug # Поможет увидеть логи прямо в консоли docker-compose 
  }
  elasticsearch {
      hosts => [ "${ES_HOST}" ]
      #index => "logs_app_gen%-%{+YYYY.MM.dd}"
      index => "logs_direct-%{+YYYY.MM.dd}"
      }
} 